project_name: agen

builds:
  - id: agen
    main: ./tools/agen/cmd/agen
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    binary: agen

archives:
  - id: default
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - dist/node-agent/**
    replacements:
      darwin: macOS

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

signs:
  - artifacts: all
    cmd: "gpg --batch --yes --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --detach-sign -a {{ .ArtifactPath }}"
    # Note: the CI must import a GPG private key and set GPG_PASSPHRASE as a secret for signing to work.

release:
  github:
    owner: TLHarnden630
    name: legendary-enigma
