name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    name: Build & Release (goreleaser)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  node-artifact:
    name: Package Node CLI
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Pack agent-cli
        working-directory: tools/agent-cli
        run: |
          npm ci --silent || true
          mkdir -p ../../dist/node-agent
          # create a zipped artifact of the Node CLI
          zip -r ../../dist/node-agent/agent-cli-${{ github.ref_name || github.sha }}.zip . -x "node_modules/*"

      - name: Upload Node artifact to release
        uses: softprops/turnstyle@v1
        with:
          # this step is a placeholder to ensure ordering; actual upload handled by goreleaser for Go
          dummy: true
